import { StringFilter } from "@react3l/advanced-filters";
import { IdFilter } from "@react3l/advanced-filters";
import { NumberFilter } from "@react3l/advanced-filters";
import { DateFilter } from "@react3l/advanced-filters";
import { GuidFilter } from "@react3l/advanced-filters";
import { ModelFilter } from "@react3l/react3l/core";

export class PurchasePlanFilter extends ModelFilter {
  public id?: IdFilter = new IdFilter();
  public code?: StringFilter = new StringFilter();
  public description?: StringFilter = new StringFilter();
  public purchaseRequestCode?: StringFilter = new StringFilter();
  public categoryId?: IdFilter = new IdFilter();
  public purchaseRequestId?: IdFilter = new IdFilter();
  public purchasePlanTypeId?: IdFilter = new IdFilter();
  public requestOrganizationId?: IdFilter = new IdFilter();
  public quotationExpectedAt?: DateFilter = new DateFilter();
  public statusId?: IdFilter = new IdFilter();
  public purchasePlanStatusId?: IdFilter = new IdFilter();
  public mainCurrencyId?: IdFilter = new IdFilter();
  public selectedSupplierId?: IdFilter = new IdFilter();
  public subTotal?: NumberFilter = new NumberFilter();
  public freightExpense?: NumberFilter = new NumberFilter();
  public totalWithoutTax?: NumberFilter = new NumberFilter();
  public total?: NumberFilter = new NumberFilter();
  public creatorId?: IdFilter = new IdFilter();
  public createdAt?: DateFilter = new DateFilter();
  public rowId?: GuidFilter = new GuidFilter();
}
